### ISSUE TITLE
won't work properly on uc20

### ISSUE THREAD

**Issue by anonymouse64** [snapcrafters/scummvm#28]
The post-refresh hook has this snippet:

```bash
if grep -q snap_core= /proc/cmdline
...
fi
```

this won't work on uc20 where we don't have `snap_core=` on the kernel command line, there you will need to use:

```
if grep -q snapd_recovery_mode= /proc/cmdline
```
instead

**Comment by lotharsm** [comment]
Thanks! Do you know if `snapd_recovery_mode` is always available or only on uc20? If we can't really rely on it's existence, I propose to use
```
  if [ grep -q snap_core= /proc/cmdline ] || [ grep -q snapd_recovery_mode= /proc/cmdline ]
```

instead.

**Comment by anonymouse64** [comment]
It's only on UC20 so your proposal looks good to me

**Comment by lotharsm** [comment]
Thanks for the feedback!

Should be fixed with 180c02666dbdc004c8ca94d817e391deefcb3a27 now.

**Comment by lotharsm** [comment]
The latest builds in the `edge` channel should have the fixed builds by now. Do you have the possibility to give this a little test? :-)

**Comment by AlanGriffiths** [comment]
Working on core20
