### ISSUE TITLE
/usr/share/libdrm/amdgpu.ids: No such file or directory

### ISSUE THREAD

**Issue by ghost** [snapcrafters/scummvm#31]
When launching on Ubuntu 21.04 with AMD Gpu

**Comment by lotharsm** [comment]
Does this affect other snaps too? Unfortunately, I don't have the proper hardware to test, but it seems unlikely that this issue is isolated to the ScummVM snap.

**Comment by AlanGriffiths** [comment]
> it seems unlikely that this issue is isolated to the ScummVM snap.

Agreed, this is a problem in Mesa. And many snaps use that. Like you I don't have the kit to test AMD.

**Comment by AlanGriffiths** [comment]
@lelecanfora are you up to a bit of hacking? This seems to be a problem that has been encountered before (with a different snap), and there's a description of how to edit the snap and test a solution. If you are able to confirm this works, it will help us fix the snap:

https://forum.snapcraft.io/t/amd-oss-graphics-drivers-missing-access-to-amdgpu-ids-file/12067/14

**Comment by ghost** [comment]
Yes I did exactly as the last message described and I encountered this other error:

```
me@me:~$ scummvm
+ [ -z /home/me/snap/scummvm/x1/.config ]
+ mkdir -p /run/user/1000/snap.scummvm/speech-dispatcher
+ /snap/scummvm/x1/usr/bin/speech-dispatcher -d -C /snap/scummvm/x1/etc/speech-dispatcher -S /run/user/1000/snap.scummvm/speech-dispatcher/speechd.sock -m /snap/scummvm/x1/usr/lib/speech-dispatcher-modules -t 30
[Sun Aug  8 20:14:38 2021 : 662534] speechd: Speech Dispatcher 0.8.8 starting
+ [ ! -f /home/me/snap/scummvm/x1/.config/scummvm/scummvm.ini ]
+ mkdir -p /home/me/snap/scummvm/x1/.config/scummvm/
+ echo [scummvm]\naspect_ratio=true\n
+ echo [cloud]\nrootpath=/home/me/snap/scummvm/current/.local/share/scummvm
+ [ ! -f /home/me/snap/scummvm/x1/.config/scummvm/.added-games-bundle ]
+ touch /home/me/snap/scummvm/x1/.config/scummvm/.added-games-bundle
+ grep -E comi|drascula|dreamweb|lure|myst|queen|sky|sword /home/me/snap/scummvm/x1/.config/scummvm/scummvm.ini
+ /snap/scummvm/x1/bin/scummvm -p /usr/share/scummvm/ --recursive --add
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
X Error:  BadAlloc
  Request Major code 146 ()
  Request Minor code 2
  Error Serial #104
  Current Serial #105
+ exec /snap/scummvm/x1/bin/scummvm
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
X Error:  BadAlloc
  Request Major code 146 ()
  Request Minor code 2
  Error Serial #104
  Current Serial #105
```

**Comment by AlanGriffiths** [comment]
@lelecanfora thanks for trying that. It is hard to tell what is happening here: I wouldn't expect `X Error:  BadAlloc` before `exec /snap/scummvm/x1/bin/scummvm`. Also, I would expect the error you quoted originally to also be after `exec /snap/scummvm/x1/bin/scummvm`.

I'll have to look more closely at the snap recipe. Could you do a couple of things?

1. With the original, unhacked snap installed post the console log leading up to `/usr/share/libdrm/amdgpu.ids: No such file or directory`
2. Post the output of `snap connections scummvm`

Thanks again for your help in investigating this problem.
