### ISSUE TITLE
Hardware volume buttons do not work when fullscreen

### ISSUE THREAD

**Issue by mcphail** [snapcrafters/scummvm#4]
Ubuntu Mate 19.10 on ThinkPad X230 (and confirmed by @popey on 20.04-pre on a ThinkPad X220). snap(d) `2.42.5`. Scummvm `2.1.1`(stable) and `2.2.0`(edge).

When the scummvm snap is running in fullscreen mode, the hardware volume and mute buttons do not work (nor does the LED light on the mute button when pressed). This resulted in painful bruising on my right deltoid muscle when my wife battered me as I woke her from sleep.

Steps to reproduce:
(1) Install scummvm snap and launch
(2) Select Options->Graphics->Fullscreen mode
(3) Attempt to use volume buttons and mute buttons

What should happen:
- Volume should adjust or mute with the buttons

What actually happens
- Angry wife punches you on the shoulder

I'll build a version using `desktop-launch` to see if it fixes this. If so, you'll have to decide whether it is worth the extra bloat.

**Comment by popey** [comment]
Note we specify pulseaudio plug, but not libpulse0, and don't modify the LD_LIBRARY_PATH as we do for others to find the libpulse.so. Perhaps that's all that is needed?

**Comment by mcphail** [comment]
Don't know. I've just made a new build and `libpulse` gets pulled in anyway, and `desktop-launch` doesn't improve matters. I presume this does what is needed for the pulseaudio setup?

**Comment by mcphail** [comment]
I wonder if it is actually an SDL problem? Looks as if it can be built against SDL2, so I'll try that.
